server:
  port: 8081

spring:
  application:
    name: server-provide


eureka:
  instance:
    hostname: localhost
    #ip-address: 192.168.98.22
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      #defaultZone: http://192.168.98.22:8761/eureka/,http://192.168.98.23:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://10.136.220.90:8761/eureka/,http://10.136.220.90:8762/eureka/
      #defaultZone: http://localhost:8761/eureka/


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000