server:
  port: 9088

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: spring-cloud-consumer
          uri: lb://hello-consumer
          predicates:
            - Path=/consumer/**
        - id: jd_route
          uri: http://jd.com/
          predicates:
            - Path=/jd

eureka:
  instance:
    #ip-address: 192.168.98.22
    prefer-ip-address: true
    #hostname: localhost
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
        #defaultZone: http://192.168.98.22:8761/eureka/,http://192.168.98.23:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8
    eureka-server-total-connections: 100
    eureka-server-total-connections-per-host: 50


logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactvie: DEBUG
    reactor.ipc.netty: DEBUG
