spring:
  application:
    name: spring-cloud-registry

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
      # 指定Eureka Client 间隔多久需要想Eureka-Server发送心跳来告知Eureka-Server该实例还存活 默认90
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false  #关闭自我保护模式（默认true），需要配到disconf中，开发环境为：false，线上环境为：true
  client:
    # 是否应该将实例注册到Eureka-Server 默认为true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
